-- SPEND: one row per status transition of an issued card. One-way, so order == spend.
-- Balance semantics: account must hold (amount + fee); `amount` is loaded onto
-- the card and is GONE for good (prepaid — the provider has it), `fee` is the
-- neobank's cut on top (unlike deposits/withdraws, where fee comes out of the
-- amount). 'failed' releases the reservation. 'closed' = user discarded the
-- card: no balance effect (the money is already gone), it only stops being
-- the active card so a new one can be issued.
CREATE TABLE IF NOT EXISTS card_orders (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nonce bigint NOT NULL,
    pubkey_x     bytea NOT NULL CHECK (octet_length(pubkey_x) = 32),
    user_id      text  NOT NULL,
    amount       bytea NOT NULL CHECK (octet_length(amount) = 32),
    fee          bytea NOT NULL CHECK (octet_length(fee) = 32),
    provider     text  NOT NULL,
    provider_ref text  NOT NULL,          -- NOT unique: one row per status transition
    status       text  NOT NULL
                 CHECK (status IN ('pending', 'succeeded', 'failed', 'closed')),
    error        text,                    -- provider failure reason, if any
    created_at   bigint NOT NULL CHECK (created_at > 0),  -- order placed at
    resolved_at  bigint                   -- this transition's time (NULL for pending)
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_card_orders_nonce
    ON card_orders(pubkey_x, nonce) WHERE status = 'pending';
CREATE INDEX idx_card_orders_pubkey ON card_orders(pubkey_x);
CREATE INDEX idx_card_orders_user_id ON card_orders(user_id);
CREATE INDEX idx_card_orders_ref ON card_orders(provider_ref, id DESC);

-- Append-only guard (fires even for service_role/superuser).
CREATE OR REPLACE FUNCTION reject_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% is not allowed on %.% (append-only)',
        TG_OP, TG_TABLE_SCHEMA, TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_card_orders_append_only
    BEFORE UPDATE OR DELETE ON card_orders
    FOR EACH ROW EXECUTE FUNCTION reject_mutation();

-- Per-user nonce sequence: every new request ('pending') must carry the
-- user's current max + 1; transitions (same nonce as their request) are exempt.
CREATE OR REPLACE FUNCTION enforce_next_nonce() RETURNS trigger AS $$
DECLARE expected bigint;
BEGIN
    IF NEW.status IS DISTINCT FROM 'pending' THEN
        RETURN NEW;
    END IF;
    EXECUTE format(
        'SELECT COALESCE(MAX(nonce), -1) + 1 FROM %I WHERE pubkey_x = $1',
        TG_TABLE_NAME
    ) INTO expected USING NEW.pubkey_x;
    IF NEW.nonce IS DISTINCT FROM expected THEN
        RAISE EXCEPTION 'bad % nonce: expected %, got %', TG_TABLE_NAME, expected, NEW.nonce;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_card_orders_nonce      -- trg_withdraws_nonce in withdraws.sql
    BEFORE INSERT ON card_orders          -- ON withdraws
    FOR EACH ROW EXECUTE FUNCTION enforce_next_nonce();
