-- DEPOSITS: one row per burned leaf withdrawn on a confirmed withdraw tx.
-- User perspective: a deposit into the neobank. Server perspective: the server
-- withdrew the underlying transfer from the burn address (worker.do_withdraw).
-- A batch withdraw shares one tx_hash/block_number across many rows; tree_index
-- is globally unique (single ever-growing tree) — idempotency key on replay.
-- fee = neobank's cut, taken out of value; user is credited (value - fee).
CREATE TABLE IF NOT EXISTS deposits (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    burn_address bytea  NOT NULL CHECK (octet_length(burn_address) = 20),
    pubkey_x     bytea  NOT NULL CHECK (octet_length(pubkey_x) = 32),
    user_id      text   NOT NULL,
    value        bytea  NOT NULL CHECK (octet_length(value) = 32),   -- gross
    fee          bytea  NOT NULL CHECK (octet_length(fee) = 32),     -- 0 if none
    tree_index   bigint NOT NULL UNIQUE CHECK (tree_index >= 0),
    tx_hash      bytea  NOT NULL CHECK (octet_length(tx_hash) = 32),
    block_number bigint NOT NULL CHECK (block_number > 0),
    created_at   bigint NOT NULL CHECK (created_at > 0)  -- withdraw tx confirmed at
);

CREATE INDEX idx_deposits_pubkey ON deposits(pubkey_x);
CREATE INDEX idx_deposits_burn_address ON deposits(burn_address);
CREATE INDEX idx_deposits_tx ON deposits(tx_hash);
CREATE INDEX idx_deposits_block ON deposits(block_number);

-- Append-only guard (fires even for service_role/superuser).
CREATE OR REPLACE FUNCTION reject_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% is not allowed on %.% (append-only)',
        TG_OP, TG_TABLE_SCHEMA, TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_deposits_append_only
    BEFORE UPDATE OR DELETE ON deposits
    FOR EACH ROW EXECUTE FUNCTION reject_mutation();
