-- WITHDRAWS: user requests to take funds out of the exchange (the payout,
-- e.g. an ERC-20 transfer to `destination`). One row per status transition:
-- current state = latest row per `ref`. Nonce = per-user sequence; each new
-- request ('pending') must carry max(nonce)+1 and consumes it — single-use
-- signatures. 'pending'/'succeeded' reserve `amount`; 'failed' releases it.
-- `destination` receives (amount - fee); fee is the neobank's cut.
CREATE TABLE IF NOT EXISTS withdraws (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref         text  NOT NULL,               -- request id, groups transitions (NOT unique)
    pubkey_x    bytea NOT NULL CHECK (octet_length(pubkey_x) = 32),
    user_id     text  NOT NULL,
    amount      bytea NOT NULL CHECK (octet_length(amount) = 32),  -- debited from balance
    fee         bytea NOT NULL CHECK (octet_length(fee) = 32),     -- kept by neobank
    destination bytea NOT NULL CHECK (octet_length(destination) = 20),
    status      text  NOT NULL
                CHECK (status IN ('pending', 'succeeded', 'failed')),
    nonce       bigint NOT NULL CHECK (nonce >= 0),
    tx_hash     bytea CHECK (tx_hash IS NULL OR octet_length(tx_hash) = 32),
    error       text,
    created_at  bigint NOT NULL CHECK (created_at > 0),  -- request placed at
    resolved_at bigint                           -- this transition's time (NULL for pending)
);

CREATE INDEX idx_withdraws_pubkey ON withdraws(pubkey_x);
CREATE INDEX idx_withdraws_user_id ON withdraws(user_id);
CREATE INDEX idx_withdraws_ref ON withdraws(ref, id DESC);
CREATE UNIQUE INDEX uniq_withdraws_nonce ON withdraws(pubkey_x, nonce);

-- Per-user nonce sequence: 'pending' inserts must be exactly max(nonce)+1.
CREATE OR REPLACE FUNCTION enforce_next_nonce() RETURNS trigger AS $$
DECLARE expected bigint;
BEGIN
    IF NEW.status IS DISTINCT FROM 'pending' THEN
        RETURN NEW;
    END IF;
    EXECUTE format(
        'SELECT COALESCE(MAX(nonce), -1) + 1 FROM %I WHERE pubkey_x = $1',
        TG_TABLE_NAME
    ) INTO expected USING NEW.pubkey_x;
    IF NEW.nonce IS DISTINCT FROM expected THEN
        RAISE EXCEPTION 'bad % nonce: expected %, got %', TG_TABLE_NAME, expected, NEW.nonce;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_withdraws_nonce
    BEFORE INSERT ON withdraws
    FOR EACH ROW EXECUTE FUNCTION enforce_next_nonce();

-- Append-only guard (fires even for service_role/superuser).
CREATE OR REPLACE FUNCTION reject_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% is not allowed on %.% (append-only)',
        TG_OP, TG_TABLE_SCHEMA, TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_withdraws_append_only
    BEFORE UPDATE OR DELETE ON withdraws
    FOR EACH ROW EXECUTE FUNCTION reject_mutation();
